# Generated by Django 5.2.6 on 2025-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterapp', '0003_alert_state_alter_alert_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
